import '../models/seller_model.dart';

class MockMarketplaceService {
  Future<List<SellerModel>> getSellers() async {
    await Future.delayed(const Duration(milliseconds: 600));
    return _mockSellers;
  }

  static final List<SellerModel> _mockSellers = [
    const SellerModel(
      id: '1',
      name: 'Dhruv Patil',
      city: 'Vadodara',
      solarCapacity: 10.0,
      pricePerKwh: 4.5,
      availableEnergy: 320,
      rating: 4.8,
      distance: 2.3,
      description: 'Premium rooftop solar installation',
    ),
    const SellerModel(
      id: '2',
      name: 'Kanishk Salunkhe',
      city: 'Vadodara',
      solarCapacity: 5.0,
      pricePerKwh: 5.0,
      availableEnergy: 180,
      rating: 4.6,
      distance: 3.1,
      description: 'Residential solar panels',
    ),
    const SellerModel(
      id: '3',
      name: 'Alok Bhadage',
      city: 'Vadodara',
      solarCapacity: 25.0,
      pricePerKwh: 3.8,
      availableEnergy: 860,
      rating: 4.9,
      distance: 5.7,
      description: 'Community solar cooperative',
    ),
    const SellerModel(
      id: '4',
      name: 'Het Gandhi',
      city: 'Mumbai',
      solarCapacity: 8.0,
      pricePerKwh: 5.2,
      availableEnergy: 240,
      rating: 4.5,
      distance: 1.8,
      description: 'Rooftop solar with battery storage',
    ),
    const SellerModel(
      id: '5',
      name: 'Solar India Corp',
      city: 'Delhi',
      solarCapacity: 50.0,
      pricePerKwh: 3.5,
      availableEnergy: 1500,
      rating: 4.7,
      distance: 8.2,
      description: 'Large scale solar farm',
    ),
    const SellerModel(
      id: '6',
      name: 'Priya Sharma',
      city: 'Pune',
      solarCapacity: 6.0,
      pricePerKwh: 4.8,
      availableEnergy: 200,
      rating: 4.4,
      distance: 4.5,
      description: 'Home solar energy producer',
    ),
    const SellerModel(
      id: '7',
      name: 'SunPower Bengaluru',
      city: 'Bengaluru',
      solarCapacity: 15.0,
      pricePerKwh: 4.2,
      availableEnergy: 520,
      rating: 4.8,
      distance: 6.1,
      description: 'Tech park rooftop solar',
    ),
    const SellerModel(
      id: '8',
      name: 'Meena Iyer',
      city: 'Chennai',
      solarCapacity: 7.0,
      pricePerKwh: 4.0,
      availableEnergy: 280,
      rating: 4.3,
      distance: 3.4,
      description: 'South-facing panels with high yield',
    ),
    const SellerModel(
      id: '9',
      name: 'Gujarat Solar Hub',
      city: 'Ahmedabad',
      solarCapacity: 20.0,
      pricePerKwh: 3.9,
      availableEnergy: 700,
      rating: 4.6,
      distance: 7.0,
      description: 'Commercial solar installation',
    ),
    const SellerModel(
      id: '10',
      name: 'Vikram Desai',
      city: 'Surat',
      solarCapacity: 12.0,
      pricePerKwh: 4.3,
      availableEnergy: 420,
      rating: 4.5,
      distance: 4.8,
      description: 'Factory rooftop solar panels',
    ),
  ];
}
